services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    volumes:
      - backend_cache:/app/cache
    models:
      - phishing-detect

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

models:
  phishing-detect:
    model: ai/llama3.2

networks:
  app-network:
    driver: bridge

volumes:
  backend_cache:
